/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fs.h"

bool_t
xdr_dados (XDR *xdrs, dados *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, 1024))
		 return FALSE;
	return TRUE;
}
